// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
// / await Firebase.initializeApp(
// /   options: DefaultFirebaseOptions.currentPlatform,
// / );
/// ```



class DefaultFirebaseOptions {

  static FirebaseOptions get currentPlatform {

    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDv235T_2YgpJhkTAjti5KSUNm-uKg_D4Q',
    appId: '1:602347638322:web:2269a44d0a95040e39f62b',
    messagingSenderId: '602347638322',
    projectId: 'challenge-coding',
    authDomain: 'challenge-coding.firebaseapp.com',
    storageBucket: 'challenge-coding.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDq2ZMXnazckGTmVeS840r4VKozDEqsiI8',
    appId: '1:602347638322:android:20698c2db22f085c39f62b',
    messagingSenderId: '602347638322',
    projectId: 'challenge-coding',
    storageBucket: 'challenge-coding.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxAGc91wPoT5hSaG-22jB1Ui9v7q9shMI',
    appId: '1:602347638322:ios:936ac89c3c45b36b39f62b',
    messagingSenderId: '602347638322',
    projectId: 'challenge-coding',
    storageBucket: 'challenge-coding.firebasestorage.app',
    iosBundleId: 'com.example.codingChallengeKoesnadi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxAGc91wPoT5hSaG-22jB1Ui9v7q9shMI',
    appId: '1:602347638322:ios:936ac89c3c45b36b39f62b',
    messagingSenderId: '602347638322',
    projectId: 'challenge-coding',
    storageBucket: 'challenge-coding.firebasestorage.app',
    iosBundleId: 'com.example.codingChallengeKoesnadi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDv235T_2YgpJhkTAjti5KSUNm-uKg_D4Q',
    appId: '1:602347638322:web:dbd9e92b72ec3a9139f62b',
    messagingSenderId: '602347638322',
    projectId: 'challenge-coding',
    authDomain: 'challenge-coding.firebaseapp.com',
    storageBucket: 'challenge-coding.firebasestorage.app',
  );
}
