// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
// / await Firebase.initializeApp(
// /   options: DefaultFirebaseOptions.currentPlatform,
// / );
/// ```

class DefaultFirebaseOptions {

  static FirebaseOptions get currentPlatform {

    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8v24DM6-7gnWeJLSfAgx_dyEtj-U6Ve0',
    appId: '1:814905777019:web:76c738eaf2d18ec0173bde',
    messagingSenderId: '814905777019',
    projectId: 'challenge-coding-koesnadi',
    authDomain: 'challenge-coding-koesnadi.firebaseapp.com',
    storageBucket: 'challenge-coding-koesnadi.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqsVz6HsSGGqO1SABtAR26-UNJyrr7eBw',
    appId: '1:814905777019:android:8c0165c345aadb35173bde',
    messagingSenderId: '814905777019',
    projectId: 'challenge-coding-koesnadi',
    storageBucket: 'challenge-coding-koesnadi.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBV4t1RykG7vmuiJXkbMHIYRA5JCgV027Y',
    appId: '1:814905777019:ios:ec27482eaf0eecc5173bde',
    messagingSenderId: '814905777019',
    projectId: 'challenge-coding-koesnadi',
    storageBucket: 'challenge-coding-koesnadi.firebasestorage.app',
    iosBundleId: 'com.example.codingChallengeKoesnadi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBV4t1RykG7vmuiJXkbMHIYRA5JCgV027Y',
    appId: '1:814905777019:ios:ec27482eaf0eecc5173bde',
    messagingSenderId: '814905777019',
    projectId: 'challenge-coding-koesnadi',
    storageBucket: 'challenge-coding-koesnadi.firebasestorage.app',
    iosBundleId: 'com.example.codingChallengeKoesnadi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8v24DM6-7gnWeJLSfAgx_dyEtj-U6Ve0',
    appId: '1:814905777019:web:17ac784ceefe161d173bde',
    messagingSenderId: '814905777019',
    projectId: 'challenge-coding-koesnadi',
    authDomain: 'challenge-coding-koesnadi.firebaseapp.com',
    storageBucket: 'challenge-coding-koesnadi.firebasestorage.app',
  );

}